package com.e4u.autoajuda.activities;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;

import com.e4u.autoajuda.R;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

public class FraseDiaActivity extends AppCompatActivity {

    TextView txtFrase;
    LinearLayout llCompartilhar;
    Context context;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_frase_dia);

        //Criar o vinculo entre as variaveis e os objetos do XML
        txtFrase = findViewById(R.id.txtFrase);

        llCompartilhar = findViewById(R.id.llCompartilhar);

        llCompartilhar.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                compartilharFrase();
            }
        });

        carregarFrases();
    }

    private void compartilharFrase(){

        Intent shareIntent = new Intent(android.content.Intent.ACTION_SEND);
        shareIntent.setType("text/plain");
        shareIntent.putExtra(android.content.Intent.EXTRA_SUBJECT, "Frase do dia do Aplicativo Auto Ajuda");
        String shareMessage = txtFrase.getText().toString();
        shareIntent.putExtra(android.content.Intent.EXTRA_TEXT, shareMessage);
        startActivity(Intent.createChooser(shareIntent, "Compartilhe a Frase do dia"));
    }

    private void carregarFrases(){

        List<String> listaFrases = new ArrayList<>();

        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“As pessoas que tentam tornar esse mundo pior não tiram um dia de folga. Como  é que vou TIRAR?”");
        listaFrases.add("“Impossível é apenas uma opinião.”- Paulo Coelho");
        listaFrases.add("“Sua paixão está esperando por sua coragem para alcançá-la”- Johann Wolfgang Von Goethe");
        listaFrases.add("“Se algo é importante o suficiente, mesmo que as probabilidades estejam contra você, você ainda deve fazê-lo.”");
        listaFrases.add("“Mantenha a visão, confie no processo.”");
        listaFrases.add("“Não tenha medo de desistir do bom para ir para o excelente.”");
        listaFrases.add("“Estou vivo, motivado e pronto para matar o dia.”");
        listaFrases.add("“Ninguém é culpado por sua situação futura, a não ser você mesmo. Se você quer ter sucesso, torne-se “Bem-sucedido”");
        listaFrases.add("“Apresse-se em silêncio e deixe seu sucesso fazer barulho.”- Aristóteles");
        listaFrases.add("“Sempre fiz algo que não estava pronto para fazer. Acho que é assim que você cresce. Quando há aquele momento de 'Uau, não tenho certeza se posso fazer isso', e você supera esses momentos, é quando você tem um avanço.”");
        listaFrases.add("“Algumas pessoas querem que aconteça, outras desejam que aconteça, outras fazem acontecer.”- Michael Jordan");
        listaFrases.add("“Grandes coisas são feitas por uma série de pequenas coisas reunidas”- Vincent Van Gogh");
        listaFrases.add("“Se você contratar pessoas apenas porque elas podem fazer um trabalho, elas trabalharão pelo seu dinheiro. Mas se você contratar pessoas que acreditam no que você acredita, elas trabalharão para você com sangue, suor e lágrimas.” - Simon Sinek");
        listaFrases.add("“Muitas vezes, uma mudança de personalidade é mais necessária do que uma mudança de cenário.”");
        listaFrases.add("“Os líderes podem deixar você falhar e ainda não permitir que você seja um fracasso.”");
        listaFrases.add("“Não é a carga que o destrói, é a maneira como você a carrega.”");
        listaFrases.add("“Os dias difíceis são o que o torna mais forte.”");
        listaFrases.add("“Se você acredita que vai dar certo, verá oportunidades. Se você não acreditar que vai funcionar, você verá obstáculos.”");
        listaFrases.add("“Mantenha os olhos nas estrelas e os pés no chão”");
        listaFrases.add("“Você tem que acordar todas as manhãs com determinação se quiser ir para a cama com satisfação.”");
        listaFrases.add("“De uma forma suave, você pode agitar o mundo.”");
        listaFrases.add("“Se a oportunidade não bater, construa uma porta.”- Kurt Cobain");
        listaFrases.add("“Não se deixe levar pelos medos em sua mente. Seja guiado pelos sonhos em seu coração.”");
        listaFrases.add("“Trabalhe duro em silêncio, deixe seu sucesso ser o ruído.”- Frank Ocean");
        listaFrases.add("“Não diga que você não tem tempo suficiente. Você tem exatamente o mesmo número de horas por dia que foram dadas a Helen Keller, Pasteur, Michelangelo, Madre Teresa, Leonardo Da Vinci, Thomas Jefferson e Albert Einstein.”- H. Jackson Brown Jr.");
        listaFrases.add("“O trabalho árduo vence o talento quando o talento não trabalha muito.”");
        listaFrases.add("“Se tudo parece estar sob controle, você não está indo rápido o suficiente.” - Mario Andretti");
        listaFrases.add("“A melhor maneira de apreciar o seu trabalho é imaginar-se sem ele.”");
        listaFrases.add("“As pessoas malsucedidas tomam suas decisões com base em suas situações atuais. Pessoas de sucesso tomam suas decisões com base em onde querem estar.”");
        listaFrases.add("“Nunca pare de fazer o seu melhor só porque alguém não lhe dá crédito.”");
        listaFrases.add("“Trabalhe duro pelo que você quer porque não vai chegar até você sem lutar. Você tem que ser forte e corajoso e saber que pode fazer qualquer coisa que colocar em sua mente. Se alguém te rebaixar ou criticar, continue acreditando em você mesmo e transforme isso em algo positivo.”");
        listaFrases.add("“Trabalhe duro, seja gentil e coisas incríveis acontecerão.”");
        listaFrases.add("“Nunca desista de um sonho só pelo tempo que vai demorar para realizá-lo. O tempo vai passar de qualquer maneira.”");
        listaFrases.add("“O grande segredo da vida é que não há segredo. Seja qual for o seu objetivo, você pode chegar lá se estiver disposto a trabalhar.”");
        listaFrases.add("“Se você não pode fazer grandes coisas, faça pequenas coisas de uma forma excelente.”");
        listaFrases.add("“Nunca permita que uma pessoa lhe diga não, sem o poder de dizer sim.”");
        listaFrases.add("“Um homem de verdade não se faz só com palavras” - Chorão");
        listaFrases.add("“A qualquer momento você tem o poder de dizer: não é assim que a história vai terminar.”");
        listaFrases.add("“Amateus senta e espera pela inspiração. O resto de nós apenas se levanta e vai trabalhar.”- Stephen King");
        listaFrases.add("“Seu trabalho vai preencher uma grande parte da sua vida, e a única maneira de ficar realmente satisfeito é fazer o que você acredita ser um ótimo trabalho. E a única maneira de fazer um ótimo trabalho é amar o que você faz. Se você ainda não encontrou, continue procurando. Não se acomode. Como acontece com todos os assuntos do coração, você saberá quando o encontrar. ”- Steve Jobs");
        listaFrases.add("“Nada funcionará a menos que você faça.”- Maya Angelou");
        listaFrases.add("“Não limite seus desafios. Desafie seus limites.”");
        listaFrases.add("“Sempre que você duvidar do quão longe você pode ir, lembre-se de quão longe você chegou.”");
        listaFrases.add("“Todo mundo tem dentro de si uma boa notícia. A boa notícia é que você não sabe o quão bom pode ser! Quanto você pode amar! O que você pode realizar! E qual é o seu potencial.”");
        listaFrases.add("“No meio de cada dificuldade está a oportunidade.”- Albert Einstein");
        listaFrases.add("“Comece onde você está. Use o que você tem. Faz o que podes.”");
        listaFrases.add("“Os sonhos não funcionam a menos que você faça.”");
        listaFrases.add("“Superar as expectativas. Nunca fica lotado lá.”");
        listaFrases.add("“Mantenha seu rosto sempre voltado para o sol - e as sombras cairão atrás de você.”");
        listaFrases.add("“O que nos define é o quão bem nos levantamos depois de cair.”");
        listaFrases.add("“O que nos define é o quão bem nos levantamos depois de cair.”- John Wooden");
        listaFrases.add("“Aonde quer que você vá, vá com todo seu coração”");
        listaFrases.add("“Transforme suas feridas em sabedoria”");
        listaFrases.add("“Podemos fazer tudo o que quisermos, se cumprirmos o tempo suficiente.”");
        listaFrases.add("“Comece em qualquer lugar.”");
        listaFrases.add("“O sucesso não é acidental. É trabalho árduo, perseverança, aprendizado, estudo, sacrifício e, acima de tudo, amor pelo que você está fazendo ou aprendendo a fazer. ”- Pelé");
        listaFrases.add("“Você gostaria que eu lhe desse uma fórmula para o sucesso? É muito simples, na verdade: dobre sua taxa de falha. Você está pensando no fracasso como inimigo do sucesso. Mas não é de todo. Você pode ficar desanimado com o fracasso ou pode aprender com ele, então vá em frente e cometa erros. Faça tudo o que puder. Porque lembre-se de que é onde você encontrará o sucesso.”");
        listaFrases.add("“Todo campeão já foi um competidor que não desistia.”");
        listaFrases.add("“Para ser um campeão, eu acho que você tem que ver o quadro geral. Não se trata de ganhar e perder; trata-se de trabalho árduo todos os dias e sobre vencer um desafio. É abraçar a dor que você sentirá no final de uma corrida e não ter medo. Acho que as pessoas pensam muito e ficam com medo de um determinado desafio.”");
        listaFrases.add("“Não sonhe com sucesso. Vá lá e trabalhe por isso.”");
        listaFrases.add("“A diferença entre pessoas de sucesso e pessoas de muito sucesso é que as pessoas de muito sucesso dizem 'não' a quase tudo.”");
        listaFrases.add("“Você pode chorar, gritar e bater a cabeça em frustração, mas continue avançando. Vale a pena.”");
        listaFrases.add("“Odiei cada minuto de treinamento, mas disse: 'Não desista. Sofra agora e viva o resto de sua vida como um campeão.”- Muhammad Ali");
        listaFrases.add("“Oportunidades não acontecem. Você os cria.”");
        listaFrases.add("“Sucesso é gostar de si mesmo, gostar do que você faz e gostar de como você faz.”");
        listaFrases.add("“Se você obedecer a todas as regras, perderá toda a diversão.”");
        listaFrases.add("“Você nasceu para ser jogador. Você deveria estar aqui. Este momento é seu.”");
        listaFrases.add("“A vida não é o que você faz sozinho. A vida é a entrada de todos que tocaram sua vida e de cada experiência que entrou nela. Somos todos parte um do outro”");
        listaFrases.add("“Quando você chegar ao fim da corda, dê um nó e relaxe.”");
        listaFrases.add("“Nunca se arrependa de nada que te fez sorrir.”");
        listaFrases.add("“Você deve fazer o que pensa que não pode fazer.”");
        listaFrases.add("“Se você quer voar, desista de tudo o que o pesa.”- Buda");
        listaFrases.add("“A dúvida mata mais sonhos do que o fracasso.”");
        listaFrases.add("“Eu nunca perco. Ou eu ganho ou aprendo.”- Nelson Mandela");
        listaFrases.add("“Hoje é sua oportunidade de construir o amanhã que você deseja.”");
        listaFrases.add("“Concentre-se em ser produtivo em vez de ocupado.”");
        listaFrases.add("“Você não precisa ver toda a escada, basta dar o primeiro passo.”- Martin Luther King Júnior.");
        listaFrases.add("“Quando alguém disser que você não pode fazer isso, faça duas vezes e tire fotos.”");
        listaFrases.add("“Não cheguei lá desejando, mas trabalhando para isso.”");
        listaFrases.add("“Se você está confortável demais, é hora de seguir em frente. Com medo do que vem a seguir? Você está no caminho certo.”");
        listaFrases.add("“Seja feliz com o que você tem enquanto trabalha pelo que você quer.”");
        listaFrases.add("“A grande lição da vida é nunca ter medo de ninguém nem de nada.”- Frank Sinatra");
        listaFrases.add("“Você é muito mais forte do que suas desculpas”");
        listaFrases.add("“Não se compare com os outros. Seja como o sol e a lua e brilhe quando for a sua hora.”");
        listaFrases.add("“Não diga a todos os seus planos, em vez disso mostre os resultados.”");
        listaFrases.add("“Eu escolho fazer do resto da minha vida, o melhor da minha vida.”");
        listaFrases.add("“Nada pode diminuir a luz que brilha de dentro.”");
        listaFrases.add("“Seja tão bom que eles não podem ignorar você.”- Steve Martin");
        listaFrases.add("“Leve as críticas a sério, mas não pessoalmente. Se houver verdade ou mérito na crítica, tente aprender com ela. Caso contrário, deixe rolar para fora de você”- Hillary Clinton");
        listaFrases.add("“Este é um lembrete para você criar seu próprio livro de regras e viver sua vida da maneira que quiser.”");
        listaFrases.add("“Se você não sair da caixa em que foi criado, não vai entender como o mundo é maior.” Angelina Jolie");
        listaFrases.add("“Faça o melhor que puder. Ninguém pode fazer mais do que isso.”");
        listaFrases.add("“Faça o que puder, com o que você tem, onde você está.”");
        listaFrases.add("“Nunca é tarde demais para ser o que você poderia ter sido.”");
        listaFrases.add("“Se consegues sonhar consegues fazê-lo.”- Walt Disney");
        listaFrases.add("“Acredite em si mesmo, que você pode fazer e conseguir.”");
        listaFrases.add("“O melhor presente Deus me deu: a vida me ensinou a lutar pelo que é meu” - Chorão");
        listaFrases.add("“Não deixe o que você não pode fazer interferir no que você pode fazer.”");
        listaFrases.add("“Você pode fazer qualquer coisa que decidir.”");
        listaFrases.add("“Tudo o que podemos fazer é o melhor que podemos fazer.”");
        listaFrases.add("“Você nunca sabe o que pode fazer até tentar.”");
        listaFrases.add("“Daqui a vinte anos, você ficará mais decepcionado com as coisas que não fez do que com as que fez.”");
        listaFrases.add("“Agradeço a todos aqueles que me disseram NÃO. É por causa deles que estou fazendo isso sozinho.”");
        listaFrases.add("“Agradeço a todos aqueles que me disseram NÃO. É por causa deles que estou fazendo isso sozinho.”");
        listaFrases.add("“O mundo está cheio de gente legal. Se você não consegue encontrar um, seja um.”");
        listaFrases.add("“Acredite em si mesmo, enfrente seus desafios, cave fundo em você mesmo para vencer os medos. Nunca deixe ninguém te derrubar. Você tem que continuar.”");
        listaFrases.add("“Uma caminhada até um parque próximo pode dar a você mais energia e inspiração na vida do que passar duas horas na frente de uma tela.”");
        listaFrases.add("“Se você não pode fazer nada a respeito, deixe para lá. Não seja prisioneiro de coisas que você não pode mudar.”");
        listaFrases.add("“Você não pode voltar e mudar o começo, mas pode começar de onde está e mudar o final.”");
        listaFrases.add("“Ontem eu era inteligente, então queria mudar o mundo. Hoje sou sábio, então estou mudando a mim mesmo.”");
        listaFrases.add("“Eu posso e vou. Me veja.”");
        listaFrases.add("“Tente não se tornar um homem de sucesso, mas sim um homem de valor.”- Albert Einstein");
        listaFrases.add("“Um vencedor é um sonhador que nunca desiste.”- Nelson Mandela");
        listaFrases.add("“A única coisa que está no caminho entre você e seu objetivo é a história de besteira que você vive contando a si mesmo sobre por que não consegue alcançá-la.”");
        listaFrases.add("“O que é a vida sem um pequeno risco?”");
        listaFrases.add("“Faça apenas o que seu coração lhe diz.”- Princesa Diana");
        listaFrases.add("“Se for uma boa ideia, vá em frente e faça. É muito mais fácil se desculpar do que obter permissão.”");
        listaFrases.add("“A questão não é quem vai me deixar; é quem vai me impedir.”");
        listaFrases.add("“Um esforço excedente pode superar um déficit de confiança.”");
        listaFrases.add("“E, quando você quer algo, todo o universo conspira para ajudá-lo a alcançá-lo.”- Paulo Coelho, O Alquimista");
        listaFrases.add("“Não pense ou julgue, apenas ouça.”");
        listaFrases.add("“As trevas não podem expulsar as trevas: só a luz pode fazer isso. O ódio não pode expulsar o ódio: só o amor pode fazer isso.”- Martin Luther King Jr.");
        listaFrases.add("“É a possibilidade de realizar um sonho que torna a vida interessante.”- Paulo Coelho, O Alquimista");
        listaFrases.add("“Há algo de bom neste mundo, e pelo qual vale a pena lutar.”");
        listaFrases.add("“Aprenda a acender uma vela nos momentos mais sombrios da vida de alguém. Seja a luz que ajuda os outros a ver; é o que dá à vida seu significado mais profundo.”");
        listaFrases.add("“Oh sim, o passado pode doer. Mas, a meu ver, você pode fugir ou aprender com ele”- O Rei Leão");
        listaFrases.add("“Estamos à beira da aventura, crianças. Não estrague isso com perguntas.”");
        listaFrases.add("“A vida passa muito rápido. Se você não parar e olhar em volta de vez em quando, pode perder.”");
        listaFrases.add("“Ninguém nunca fez a diferença sendo como todo mundo.”");
        listaFrases.add("“Passe um pouco mais de tempo tentando fazer algo de você mesmo e menos tempo tentando impressionar as pessoas.”");
        listaFrases.add("“O problema não é o problema. O problema é a sua atitude sobre o problema.”Piratas do Caribe");
        listaFrases.add("“A vida é um jogo para todos e o amor é o prêmio”");
        listaFrases.add("“Hoje é onde seu livro começa, o resto ainda não foi escrito.”");
        listaFrases.add("“É a minha vida, é agora ou nunca, não vou viver para sempre. Só quero viver enquanto estou vivo ”- It's My Life, Bon Jovi");
        listaFrases.add("“Eu poderia construir um castelo com todos os tijolos que eles jogaram em mim”");
        listaFrases.add("“Não se comprometa. Você é tudo que você tem.”");
        listaFrases.add("“Aprenda com os erros dos outros. Você não pode viver o suficiente para fazê-los todos sozinho.”");
        listaFrases.add("“Feito é melhor que perfeito.”");
        listaFrases.add("“Se seus sonhos não te assustam, eles são muito pequenos.”");
        listaFrases.add("“Hoje é sua oportunidade de construir o amanhã que você deseja.”");
        listaFrases.add("“O que te machuca te abençoa.”");
        listaFrases.add("“Nada é mais forte do que um homem destruído se reconstruindo.”");
        listaFrases.add("“Sempre pensei que era eu contra o mundo e um dia percebi que era só eu contra mim.”");
        listaFrases.add("“Um homem não está acabado quando é derrotado. Ele está acabado quando ele desiste.”");
        listaFrases.add("“O mundo mudou com o seu exemplo, não com a sua opinião.”- Paulo Coelho");
        listaFrases.add("“Se você não construir o seu sonho, outra pessoa o contratará para ajudá-los a construir o deles.”");
        listaFrases.add("“Não estou neste mundo para corresponder às suas expectativas e você não está neste mundo para corresponder às minhas.”- Bruce Lee");
        listaFrases.add("“O que é certo é o que sobra se você fizer todo o resto errado”- Robin Williams");
        listaFrases.add("“Sonhe lindos sonhos e depois trabalhe para torná-los realidade.”");
        listaFrases.add("“Seja a mudança que você quer ver no mundo.”");
        listaFrases.add("“Saber dar valor para as coisas mais simples, só o amor constrói pontes indestrutíveis” - Chorão");
        listaFrases.add("“Acredite que você pode e você conseguirá.”");
        listaFrases.add("“Faça a coisa certa mesmo quando ninguém está olhando.”");
        listaFrases.add("“Faça de hoje o dia em que você aprenderá algo novo.”");
        listaFrases.add("“Seja bobo, seja honesto, seja gentil.”");
        listaFrases.add("“Se você acha que alguém poderia usar um amigo. Seja um.”");
        listaFrases.add("“Não é o que acontece com você, mas como você reage a isso que importa.”");
        listaFrases.add("“Você não precisa ser perfeito para ser incrível.”");
        listaFrases.add("“A melhor maneira de prever seu futuro é criá-lo.”");
        listaFrases.add("“Pessoas de sucesso não são talentosas; eles apenas trabalham duro, então têm sucesso de propósito.”");
        listaFrases.add("“Não olhe para o relógio; faça o que ele faz. Continue.”");
        listaFrases.add("“Trabalhe até que seus rivais se tornem ídolos.”");
        listaFrases.add("“Você não pode ter um sonho de um milhão de dólares com uma ética de trabalho de salário mínimo.”");
        listaFrases.add("“Você deve fazer o tipo de coisas que acha que não pode fazer.”");
        listaFrases.add("“Não é o que você faz de vez em quando, é o que você faz todos os dias que faz a diferença.”");
        listaFrases.add("“Riqueza não significa ter muito dinheiro, mas sim muitas opções.”");
        listaFrases.add("“Pode haver pessoas que têm mais talento do que você, mas não há desculpa para ninguém trabalhar mais duro do que você.”");
        listaFrases.add("“Acho a televisão muito educativa. Cada vez que alguém liga, vou para a outra sala e leio um livro.”");
        listaFrases.add("“A oportunidade não bate, ela se apresenta quando você bate na porta.”");
        listaFrases.add("“É só quando arriscamos, que nossas vidas melhoram. O risco inicial e mais difícil que precisamos correr é nos tornarmos honestos.”");
        listaFrases.add("“A aventura da vida é aprender. O propósito da vida é crescer. A natureza da vida é mudar. O desafio da vida é superar. A essência da vida é cuidar. A oportunidade de gostar é servir. O segredo da vida é ousar. O tempero da vida é fazer amizade. A beleza da vida é doar.”");
        listaFrases.add("“Quando você conhece o seu valor, ninguém pode fazer você se sentir inútil.”");
        listaFrases.add("“Se você nunca comeu chorando, não sabe como é o gosto da vida.”");
        listaFrases.add("“Se você julga as pessoas, não tem tempo para amá-las.”- Mãe Teresa");
        listaFrases.add("“Os dois dias mais importantes da sua vida são o dia em que você nasce e o dia em que descobre por quê.”");
        listaFrases.add("“Podemos ver através dos outros apenas quando podemos ver através de nós mesmos. ” - Bruce Lee");
        listaFrases.add("“Você não é pago pela hora. Você é pago pelo valor que traz para a hora.”");
        listaFrases.add("“Seja um incentivador: quando você incentiva os outros, você aumenta sua autoestima, aumenta sua autoconfiança, os faz trabalhar mais, eleva seu espírito e os torna bem-sucedidos em seus empreendimentos. O incentivo vai direto ao coração e está sempre disponível. Seja um encorajador. Sempre.”");
        listaFrases.add("“Lembre-se de que você se critica há anos e não funcionou. Tente se aprovar e veja o que acontece.”");
        listaFrases.add("“Trabalhe duro e não perca a esperança. Esteja aberto a críticas e continue aprendendo. Cerque-se de pessoas felizes, calorosas e genuínas.”");
        listaFrases.add("“Seja verdadeiro consigo mesmo, mas sempre aberto para aprender. Trabalhe duro e nunca desista de seus sonhos, mesmo quando ninguém mais acredita que eles podem se tornar realidade, exceto você. Não são clichês, mas ferramentas reais de que você precisa, não importa o que faça na vida, para manter o foco no seu caminho.”");
        listaFrases.add("“Você pode controlar duas coisas: sua ética de trabalho e sua atitude sobre qualquer coisa.”");
        listaFrases.add("“O sucesso nem sempre tem a ver com grandeza. É uma questão de consistência. O trabalho árduo consistente leva ao sucesso. A grandeza virá.”");
        listaFrases.add("“Primeiro, lembre-se de olhar para as estrelas e não para os pés. Dois, nunca desista do trabalho. O trabalho lhe dá sentido e propósito e a vida é vazia sem ele. Três, se você tiver sorte o suficiente para encontrar o amor, lembre-se de que ele está lá e não o jogue fora.”");
        listaFrases.add("“Algumas mulheres optam por seguir os homens, e algumas mulheres optam por seguir seus sonhos. Se você está se perguntando qual caminho seguir, lembre-se de que sua carreira nunca vai acordar e dizer que não te ama mais.”Lady Gaga");
        listaFrases.add("“Eu realmente aprecio as pessoas que me corrigem, porque sem elas, eu poderia ter repetido erros por muito tempo.”");
        listaFrases.add("“A motivação vem de trabalhar em coisas com as quais nos preocupamos.”");
        listaFrases.add("“Se hoje você está um pouco melhor do que ontem, isso é o suficiente.”");
        listaFrases.add("“A educação é a arma mais poderosa que você pode usar para mudar o mundo.”- Nelson Mandela");
        listaFrases.add("“Se você não pode cometer um erro, não pode cometer nada.”");
        listaFrases.add("“A prática faz com que o progresso não seja perfeito.”");
        listaFrases.add("“Você pode ficar desapontado se falhar, mas estará condenado se não tentar.”");
        listaFrases.add("“O fracasso é a mensalidade que você paga pelo sucesso.”");
        listaFrases.add("“Se esperarmos até que estejamos prontos, estaremos esperando pelo resto de nossas vidas.”");
        listaFrases.add("“Estude enquanto os outros dormem; trabalhe enquanto outros estão vagando; prepare enquanto outros estão jogando; e sonhe enquanto os outros desejam.”");
        listaFrases.add("“A melhor vingança é o sucesso massivo.”- Frank Sinatra");
        listaFrases.add("“O que há do outro lado do medo? Nada.”");
        listaFrases.add("“Desistentes nunca ganham. Vencedores nunca desistem”");
        listaFrases.add("“Não é o seu salário que o torna rico, são os seus hábitos de consumo.”");
        listaFrases.add("“Se não houver vento, reme.”");
        listaFrases.add("“Nunca é tarde demais para um novo começo em sua vida.”");
        listaFrases.add("“Ação é a chave fundamental para todo o sucesso.”- Pablo Picasso");
        listaFrases.add("“Nunca sonhei com sucesso. Eu trabalhei para isso.”");
        listaFrases.add("“Uma meta é um sonho com um prazo.”");
        listaFrases.add("“Seja a mudança que você deseja ver no mundo.”");
        listaFrases.add("“Nunca duvide que um pequeno grupo de cidadãos atenciosos e comprometidos pode mudar o mundo. Na verdade, é a única coisa que sempre aconteceu.”");
        listaFrases.add("“Mudar é doloroso, mas nada é tão doloroso quanto ficar preso em algum lugar ao qual você não pertence.”");
        listaFrases.add("“Aqueles que não podem mudar de ideia não podem mudar nada.”");
        listaFrases.add("“Todo mundo pensa em mudar o mundo, mas ninguém pensa em mudar a si mesmo.”");
        listaFrases.add("“Mudança é a lei da vida. E aqueles que olham apenas para o passado ou presente, certamente perderão o futuro.”");
        listaFrases.add("“Nós nos encantamos com a beleza da borboleta, mas raramente admitimos as mudanças pelas quais ela passou para alcançar essa beleza.”");
        listaFrases.add("“Os sonhos são as sementes da mudança. Nada cresce sem uma semente e nada muda sem um sonho.”");
        listaFrases.add("“Aqui estão os loucos. Os desajustados. Os rebeldes. Os encrenqueiros. Os pinos redondos nos orifícios quadrados. Aqueles que veem as coisas de forma diferente. Eles não gostam de regras. E eles não têm nenhum respeito. Você pode citá-los, discordar deles, glorificá-los ou caluniá-los. Praticamente a única coisa que você não pode fazer é ignorá-los. Porque eles mudam as coisas. Eles empurram a raça humana para a frente. E embora alguns possam vê-los como loucos, nós vemos um gênio. Porque as pessoas que são loucas o suficiente para pensar que podem mudar o mundo são as que o fazem.”");
        listaFrases.add("“Você deve obter controle sobre seu dinheiro ou a falta dele o controlará para sempre.”");
        listaFrases.add("“Esse homem é o mais rico cujos prazeres são mais baratos.”");
        listaFrases.add("“O dinheiro é apenas uma ferramenta. Ele o levará para onde desejar, mas não o substituirá como o motorista.”");
        listaFrases.add("“Você já é um operador financeiro. Você pode não pensar nisso apenas dessa maneira, mas se você trabalha para viver, está trocando seu tempo por dinheiro. Francamente, é o pior negócio que você pode fazer. Por quê? Você sempre pode conseguir mais dinheiro, mas não pode conseguir mais tempo.”");
        listaFrases.add("“Você só pode se tornar verdadeiramente realizado em algo que ama. Não faça do dinheiro seu objetivo. Em vez disso, busque as coisas que você ama fazer e faça-as tão bem que as pessoas não consigam tirar os olhos de você.”");
        listaFrases.add("“Não desista, não leve nada para o lado pessoal e não aceite um não como resposta.”");
        listaFrases.add("“Não fique chateado quando as pessoas rejeitam você. Coisas boas são rejeitadas o tempo todo por pessoas que não podem pagar por elas.”");
        listaFrases.add("“O segredo da mudança é concentrar toda a sua energia, não em lutar contra o velho, mas em construir o novo.”- Sócrates");
        listaFrases.add("“Sua ação positiva combinada com o pensamento positivo resulta em sucesso.”");
        listaFrases.add("“O sucesso não é acidental. É muito trabalho, perseverança, aprendizado, estudo, sacrifício e acima de tudo, amor pelo que você está fazendo ou aprendendo a fazer ”- Pelé");
        listaFrases.add("““Se você falar sobre isso, é um sonho. Se você imaginar, é possível. Se você agendar, é real.”");
        listaFrases.add("“Esqueça suas desculpas. Você quer muito ou não quer nada.”");
        listaFrases.add("“A chave do sucesso é começar antes de estar pronto.”");
        listaFrases.add("“Quero ser lembrado como aquele que tentou.”");
        listaFrases.add("“Tempo é o que mais queremos e o que usamos de pior.”");
        listaFrases.add("“Não se trata de ter tempo suficiente, mas de arranjar tempo suficiente.”");
        listaFrases.add("“Tempo é dinheiro.”- Benjamin Franklin");
        listaFrases.add("“Melhor três horas antes do que um minuto atrasado.”- William Shakespeare");
        listaFrases.add("“O problema é que você acha que tem tempo.”-Buda");
        listaFrases.add("“O medo cega os nossos sonhos”- Chorão");
        listaFrases.add("“O maior presente que você poderia dar a alguém é o seu tempo. Porque quando você dá o seu tempo, está dando uma parte da sua vida que você não pode recuperar.”");
        listaFrases.add("“A pontualidade não se limita apenas a chegar ao local na hora certa, mas também a agir na hora certa.”");
        listaFrases.add("“Você não pode deixar suas falhas definirem você. Você tem que deixar suas falhas te ensinarem.”- Barack Obama");
        listaFrases.add("“O sucesso é um péssimo professor. Ele seduz pessoas inteligentes a pensar que não podem perder.”- Bill Gates");
        listaFrases.add("“Pare de ter medo do que pode dar errado e comece a ficar animado com o que pode dar certo.”");
        listaFrases.add("“A derrota é um estado de espírito; ninguém é derrotado até que a derrota seja aceita como uma realidade.”- Bruce Lee");
        listaFrases.add("“Nossa maior glória não é nunca cair, mas nos elevar sempre que caímos”");
        listaFrases.add("“É impossível viver sem falhar em alguma coisa, a menos que você viva com tanto cuidado que poderia muito bem não ter vivido - nesse caso, você falha por padrão.”");
        listaFrases.add("“O sucesso é ir de fracasso em fracasso sem perder o entusiasmo”");
        listaFrases.add("“A vida me ensinou a nunca desistir. Nem ganhar, nem perder, mas procurar evoluir” - Chorão");
        listaFrases.add("“Por que lamentamos as falhas por mais tempo do que comemoramos as vitórias?”");
        listaFrases.add("“O fracasso não é o fim do caminho. É uma grande bandeira vermelha dizendo a você 'Caminho errado. Vire-se.”");
        listaFrases.add("“Sempre que você se sentir um fracasso, lembre-se de que até a Coca Cola vendeu apenas 25 garrafas no primeiro ano”");
        listaFrases.add("“Não importa o que as pessoas digam, palavras e ideias podem mudar o mundo. ”- Robin Williams");
        listaFrases.add("“A vida é como andar de bicicleta. Para manter o equilíbrio, você deve continuar se movendo.”- Albert Einstein");
        listaFrases.add("“Uma mente negativa nunca lhe dará uma vida positiva.”");
        listaFrases.add("“No final do dia, podemos suportar muito mais do que pensamos que podemos.”");
        listaFrases.add("“Corra o risco ou perca a chance.”");
        listaFrases.add("“Nunca se arrependa de um dia em sua vida. Os dias bons trazem felicidade e os dias ruins proporcionam experiência.”");
        listaFrases.add("“Ou você comanda o dia, ou o dia comanda você.”");
        listaFrases.add("“Só eu posso mudar minha vida. Ninguém pode fazer isso por mim.”");
        listaFrases.add("“Muito pouco é necessário para ter uma vida feliz; está tudo dentro de você, na sua maneira de pensar.”- Marco Aurélio");
        listaFrases.add("“A vida é uma aventura ousada ou nada.”");
        listaFrases.add("“Sempre terá alguma dor em você, mais nunca desista. Você quer, você pode, e só superar” - Chorão");
        listaFrases.add("“A mulher que segue a multidão geralmente não vai além da multidão. A mulher que anda sozinha provavelmente se encontrará em lugares onde ninguém esteve antes”- Albert Einstein");
        listaFrases.add("“Um leitor vive mil vidas antes de morrer. O homem que nunca lê vive apenas um.”");
        listaFrases.add("“Nunca pare de aprender porque a vida nunca para de ensinar.”");
        listaFrases.add("“A capacidade de aprender é uma dádiva; a capacidade de aprender é uma habilidade; a vontade de aprender é uma escolha.”");
        listaFrases.add("“O homem que não lê não tem vantagem sobre o homem que não sabe ler.”");
        listaFrases.add("“Aprender um idioma é ter mais uma janela de onde olhar o mundo.”");
        listaFrases.add("“Eu ainda estou aprendendo.” - Michelangelo");
        listaFrases.add("“Viva como se você fosse morrer amanhã. Aprenda como se você fosse viver para sempre.”");
        listaFrases.add("“A educação é a arma mais poderosa que você pode usar para mudar o mundo.”- Nelson Mandela");
        listaFrases.add("“A força não vem da vitória. Suas lutas desenvolvem seus pontos fortes. Quando você passa por dificuldades e decide não se render, isso é força.”- Arnold Schwarzenegger");
        listaFrases.add("“Se não te desafia, não te muda.”");
        listaFrases.add("“Um sonho não se torna realidade por meio da magia; é preciso suor, determinação e trabalho duro.”");
        listaFrases.add("“As flores voltam a crescer mesmo depois dos invernos mais rigorosos. Você também vai.”");
        listaFrases.add("“O que está chegando é melhor do que o que acabou.”");
        listaFrases.add("“Sua mente é poderosa. Quando você o preencher com pensamentos positivos, todo o seu mundo mudará.”");
        listaFrases.add("“Seu único limite é sua mente.”");
        listaFrases.add("“Pare de ter medo do que pode dar errado e comece a ser positivo sobre o que pode dar certo.”");
        listaFrases.add("“Uma coisa é certa, se você não jogar, você não ganha.”");
        listaFrases.add("“O talento vence jogos, mas o trabalho em equipe vence campeonatos.”- Michael Jordan");
        listaFrases.add("“Um campeão tem medo de perder. Todo mundo tem medo de vencer.”");
        listaFrases.add("“Um vencedor é um sonhador que nunca desiste.”- Nelson Mandela");
        listaFrases.add("“O segredo do seu futuro está escondido na sua rotina diária.”");
        listaFrases.add("“Os perdedores desistem quando falham. Os vencedores fracassam até terem sucesso.”");
        listaFrases.add("“Não pare quando estiver cansado. Pare quando terminar.”");
        listaFrases.add("“Não conte às pessoas sobre seus sonhos. Mostre a eles seus sonhos.”");
        listaFrases.add("“Pode não ser fácil, mas valerá a pena.”");
        listaFrases.add("“Você nunca estará sempre motivado, então você deve aprender a ser disciplinado.”");
        listaFrases.add("“Não sou um produto das minhas circunstâncias. Eu sou um produto de minhas decisões.”");
        listaFrases.add("“Os dias difíceis são o que o torna mais forte.”");
        listaFrases.add("“Se você acredita que vai dar certo, verá oportunidades. Se você não acreditar que vai funcionar, você verá obstáculos.”");
        listaFrases.add("“Não tenha medo de tentar, tenha medo de não tentar e ver que a vida passou e você não se arriscou como deveria” - Chorão");
        listaFrases.add("“Na minha vida nem tudo acontece, mas quanto mais a gente rala, mais a gente cresce” - Chorão");
        // DUPLICADAS
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        
        Calendar calendar = Calendar.getInstance();
        int selected = calendar.get(Calendar.DAY_OF_YEAR);
        String frase = listaFrases.get(selected);
        txtFrase.setText(frase);
    }
}