package com.e4u.autoajuda.activities;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;

import com.e4u.autoajuda.R;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

public class FraseAmorActivity extends AppCompatActivity {

    TextView txtFraseAmor;
    LinearLayout llCompartilharFraseAmor;
    Context context;
    ImageView imgFrasesAmor;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_frase_amor);

        txtFraseAmor = findViewById(R.id.txtFraseAmor);
        imgFrasesAmor = findViewById(R.id.imgFrasesAmor);
        llCompartilharFraseAmor = findViewById(R.id.llCompartilharFraseAmor
        );

        Animation anim1 = AnimationUtils.loadAnimation(this, R.anim.image_fade_animation);
        txtFraseAmor.setAnimation(anim1);

        Animation anim2 = AnimationUtils.loadAnimation(this, R.anim.image_fade_animation_2);
        txtFraseAmor.setAnimation(anim2);

        Animation anim3 = AnimationUtils.loadAnimation(this, R.anim.image_fade_animation_3);
        llCompartilharFraseAmor.setAnimation(anim3);

        llCompartilharFraseAmor.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {

                compartilharFrase();
            }
        });

        loadFraseDiaAmor();
    }


    private void compartilharFrase() {

        Intent shareIntent = new Intent(android.content.Intent.ACTION_SEND);
        shareIntent.setType("text/plain");
        shareIntent.putExtra(android.content.Intent.EXTRA_SUBJECT, "Frase de Amor");
        String shareMessage = txtFraseAmor.getText().toString();
        shareIntent.putExtra(android.content.Intent.EXTRA_TEXT, shareMessage);
        startActivity(Intent.createChooser(shareIntent, "Compartilhe a Frase"));
    }

    private void loadFraseDiaAmor() {

        List<String> listaFrases = new ArrayList<>();

        listaFrases.add("Acho que a perfeição do amor é que ele não é perfeito.");
        listaFrases.add("As melhores e mais belas coisas deste mundo não podem ser vistas ou ouvidas, mas devem ser sentidas com o coração.");
        listaFrases.add("A vida sem amor é como uma árvore sem flores ou frutos.");
        listaFrases.add("A melhor coisa para se agarrar na vida são uns aos outros.");
        listaFrases.add("É melhor ter amado e perdido tempo do que nunca ter amado.");
        listaFrases.add("Você sabe que está apaixonado quando não consegue dormir porque a realidade é finalmente melhor do que seus sonhos.");
        listaFrases.add("O amor não reconhece barreiras. Ele pula obstáculos, pula cercas, penetra paredes para chegar ao seu destino cheio de esperança.");
        listaFrases.add("Ser profundamente amado por alguém lhe dá força, enquanto amar alguém profundamente lhe dá coragem.");
        listaFrases.add("Quando te vi me apaixonei e você sorriu porque sabia disso.");
        listaFrases.add("O verdadeiro amante é o homem(a mulher) que pode emocioná-lo beijando sua testa, sorrindo em seus olhos ou apenas olhando para o nada.");
        listaFrases.add("Tudo o que você precisa é amor. Mas um pouco de chocolate de vez em quando não faz mal.");
        listaFrases.add("Juro que não poderia te amar mais do que amo agora, mas sei que amarei amanhã.");
        listaFrases.add("Em sua vida vivem meus sonhos infinitos.");
        listaFrases.add("Em todo o mundo, não há coração para mim como o seu. Em todo o mundo, não há amor por você como o meu.");
        listaFrases.add("Eu amo como ela(ele) me faz sentir que tudo é possível, ou que a vida vale a pena.");
        listaFrases.add("Amar ou ter amado, basta. Não pergunte mais nada. Não há outra pérola a ser encontrada nas dobras escuras da vida.");
        listaFrases.add("Você me enfeitiçou de corpo e alma, e eu amo, amo, amo você.");
        listaFrases.add("Se você viver até os cem anos, quero viver até os cem menos um dia, para nunca ter que viver sem você.");
        listaFrases.add("Algumas histórias de amor não são romances épicos. Alguns são contos. Mas isso não os torna menos cheios de amor.");
        listaFrases.add("Você é meu coração, minha vida, meu único pensamento.");
        listaFrases.add("Com o mundo inteiro desmoronando, escolhemos esse momento para nos apaixonar.");
        listaFrases.add("Seja qual for a nossa alma, a dele(a) e a minha são iguais.");
        listaFrases.add("Nunca tive um momento de dúvida. Eu te amo. Eu acredito em você completamente. Você é meu querido(a). Minha razão de vida.");
        listaFrases.add("Você deve ser beijada(o) e frequentemente, e por alguém que sabe como. Eu!");
        listaFrases.add("Se eu te amasse menos, talvez pudesse falar mais sobre isso.");
        listaFrases.add("Eu te amo? Meu Deus, se o seu amor fosse um grão de areia, o meu seria um universo de praias.");
        listaFrases.add("Eu sou quem sou por sua causa.");
        listaFrases.add("Eu só quero que você saiba que você é muito especial ... e a razão pela qual estou te dizendo é que eu não sei se alguém já fez isso.");
        listaFrases.add("Lembre-se, somos apaixonados, então não há problema em me beijar a qualquer momento que você desejar e quiser :)");
        listaFrases.add("Eu te amo. Eu soube no primeiro minuto em que te conheci.");
        listaFrases.add("Amamos com um amor que era mais do que amor.");
        listaFrases.add("Eu te amo contra a razão, contra a promessa, contra a paz, contra a esperança, contra a felicidade, contra todo o desânimo que pudesse existir.");
        listaFrases.add("Se eu sei o que é amor, é por sua causa.");
        listaFrases.add("O amor não é apenas algo que você sente, é algo que você faz.");
        listaFrases.add("Eu te amo não por causa de quem você é, mas por causa de quem eu sou quando estou com você.");
        listaFrases.add("Amor é o que você passou com alguém.");
        listaFrases.add("Amor é quando você conhece alguém que lhe conta algo novo sobre você.");
        listaFrases.add("O amor não domina; ele cultiva");
        listaFrases.add("Estamos mais vivos quando estamos apaixonados.");
        listaFrases.add("Nunca ame ninguém que você trata como se essa pessoa fosse comum.");
        listaFrases.add("Amar é nada para ser amado é algo ... amar e ser amado é tudo.");
        listaFrases.add("Dentro de você eu me perco. Sem você, eu me vejo querendo me perder novamente.");
        listaFrases.add("Todos os dias e noites, minha mente está repleta de pensamentos sobre você. Enquanto o sol continuar a brilhar, você pode ter certeza de que meu coração continuará sendo seu.");
        listaFrases.add("Para sempre é muito tempo, mas não me importaria de passar ao seu lado.");
        listaFrases.add("Dê-me um beijo e eu farei uma serenata para você entre as estrelas. Dê-me seu amor e arrancarei cada estrela para colocá-la a seus pés.");
        listaFrases.add("Mal posso esperar ... para passar o resto da minha vida com você.");
        listaFrases.add("Eu olho para você e vejo o resto da minha vida diante dos meus olhos.");
        listaFrases.add("Eu amo seus abraços onde você simplesmente não quer deixar-me ir.");
        listaFrases.add("Eu amo você a cada passo que caminho.");
        listaFrases.add("Eu te amo por tudo o que você é, tudo o que você foi e tudo o que ainda vai ser.");
        listaFrases.add("Eu te amo desde o primeiro dia.");
        listaFrases.add("Te amei ontem, ainda te amo. Sempre amei e sempre irei amar.");
        listaFrases.add("Eu nunca quis ser sua vida inteira - apenas sua parte favorita.");
        listaFrases.add("Eu vi que você era perfeito(a) e então te amei. Então eu vi que você não era perfeito(a) e te amei ainda mais.");
        listaFrases.add("Eu quero estar em seus braços, onde você me abraça forte e nunca me deixa ir.");
        listaFrases.add("Eu quero estar com você até o sol cair no céu.");
        listaFrases.add("Eu quero você. Tudo em você. Suas falhas. Seus erros. Suas imperfeições. Eu quero você e somente você.");
        listaFrases.add("Eu andaria pelo deserto, eu andaria pelo corredor, eu nadaria todos os oceanos só para ver você sorrir.");
        listaFrases.add("Se o nosso amor fosse um livro de histórias, nos encontraríamos na primeira página.");
        listaFrases.add("Se você fosse um filme, eu assistiria você indefinidamente. Eu poderia assistir você todos os dias da minha vida e nunca ficar entediado.");
        listaFrases.add("Sou muito mais eu quando estou com você.");
        listaFrases.add("Meu coração é perfeito porque você está dentro dele.");
        listaFrases.add("Minha mente pensa em você no segundo em que adormeço e assim que acordo todas as manhãs.");
        listaFrases.add("Pensar em você me mantém acordado. Sonhar com você me mantém dormindo. Estar com você me mantém vivo.");
        listaFrases.add("Espero que saiba que toda vez que eu digo para você chegar em casa em segurança, se aquecer, ter um bom dia ou dormir bem, o que realmente estou dizendo é que te amo. Eu te amo tanto que estou começando a roubar o significado de outras palavras.");
        listaFrases.add("Quando eu olho profundamente em sua mente, encontro a beleza de mil diamantes. Enquanto eu deixava aquele amor e beleza inundarem meu corpo, eu sabia que não havia nada pelo qual eu trocaria nosso relacionamento.");
        listaFrases.add("Quando digo que te amo, não digo por hábito. Digo isso para lembrá-lo de que você é a melhor coisa que já me aconteceu.");
        listaFrases.add("Quando você se sentir sozinho(a), basta olhar para os espaços entre seus dedos e lembrar que é onde os meus se encaixam perfeitamente.");
        listaFrases.add("Sempre que você estiver tendo um dia ruim, lembre-se disto: EU TE AMO.");
        listaFrases.add("Você é meu melhor amigo(amiga), meu diário humano e minha outra metade. Você significa o mundo para mim e eu te amo.");
        listaFrases.add("Você é meu mundo!!!");
        listaFrases.add("Você NÃO tem ideia de como meu coração dispara quando vejo você.");
        listaFrases.add("Você nunca deixa de me surpreender. Todos os dias há algo novo que me faz amá-lo ainda mais do que no dia anterior.");
        listaFrases.add("Não me insista para deixá-lo ou voltar atrás de você. Onde você for, eu irei. Onde você ficar, eu ficarei.");
        listaFrases.add("Você é meu templo. Você é meu padre. Você é minha oração. Você é minha libertação.");
        listaFrases.add("Eu preferia ter você por um pouco de tempo do que por nada. Vou lembrar de você perfeitamente. Minha memória vai tocar sua pele, seus lábios. A memória vai doer, mas será minha. ");
        listaFrases.add("Não importa o que aconteça, eu nunca, nem em mil resultados trágicos, nunca me arrependerei de te amar");
        listaFrases.add("Eu quero tudo com você. Eu quero você. Eu quero isso para sempre.");
        listaFrases.add("Eu não vou longe. Eu sempre estarei aqui. Apenas um centímetro de distância. Eu prometo");
        listaFrases.add("O amor deve parecer a primeira vez que você galope um cavalo. Deve fazer seu sangue cantar. Deve assustar você. E alguma parte de você deve reconhecê-lo na primeira vez que encontrar os olhos da outra pessoa. ");
        listaFrases.add("Beijar você é meu hobby favorito. Segurar você é meu passatempo favorito.");
        listaFrases.add("De tirar o fôlego deve significar VOCÊ no dicionário.");
        listaFrases.add("Não faz muito tempo eu estava sozinho e perdido, e então você apareceu e eu estava em casa. Obrigado por me encontrar.");
        listaFrases.add("Certamente, estou sendo recompensado porque tenho você.");
        listaFrases.add("Em seus braços amorosos está o paraíso na terra.");
        listaFrases.add("Você pode não ser perfeito, você é imperfeito como todos os humanos. Mas você é perfeito para mim e isso é o que importa.");
        listaFrases.add("Prometo cuidar do seu coração com cuidado e guardá-lo com amor.");
        listaFrases.add("Ninguém jamais saberá como você é perfeito para mim.");
        listaFrases.add("Você vai caber perfeitamente confortável em meus braços por toda a eternidade, meu amor.");
        listaFrases.add("Eu vou caminhar com você e te seguir até o fim. Você é o vencedor e o único dono do meu coração.");
        listaFrases.add("O poder do seu sorriso nunca deve ser subestimado. Isso derrete meu coração e toca minha alma.");
        listaFrases.add("Seu sorriso é inebriante. Isso perdura, cativa meu coração.");
        listaFrases.add("Uma e outra vez eu tenho que me beliscar quando vejo você ao meu lado. Você é meu sonho tornado realidade.");
        listaFrases.add("Você é único(a) para mim. Nunca tive tanta certeza de nada em toda a minha vida.");
        listaFrases.add("Esperei tanto pela pessoa perfeita e minha paciência finalmente valeu a pena.");
        listaFrases.add("Você não pode fazer nada de errado aos meus olhos. Você é perfeito!");
        listaFrases.add("Posso não ser perfeito, mas sempre deixo você estar certo. E eu sei que não estou errado sobre isso!");
        listaFrases.add("Eu te amo mais do que amo ficar bêbado. E eu realmente adoro ficar bêbado.");

        listaFrases.add("Acho que a perfeição do amor é que ele não é perfeito.");
        listaFrases.add("As melhores e mais belas coisas deste mundo não podem ser vistas ou ouvidas, mas devem ser sentidas com o coração.");
        listaFrases.add("A vida sem amor é como uma árvore sem flores ou frutos.");
        listaFrases.add("A melhor coisa para se agarrar na vida são uns aos outros.");
        listaFrases.add("É melhor ter amado e perdido tempo do que nunca ter amado.");
        listaFrases.add("Você sabe que está apaixonado quando não consegue dormir porque a realidade é finalmente melhor do que seus sonhos.");
        listaFrases.add("O amor não reconhece barreiras. Ele pula obstáculos, pula cercas, penetra paredes para chegar ao seu destino cheio de esperança.");
        listaFrases.add("Ser profundamente amado por alguém lhe dá força, enquanto amar alguém profundamente lhe dá coragem.");
        listaFrases.add("O verdadeiro amante é o homem(a mulher) que pode emocioná-lo beijando sua testa, sorrindo em seus olhos ou apenas olhando para o nada.");
        listaFrases.add("Tudo o que você precisa é amor. Mas um pouco de chocolate de vez em quando não faz mal.");
        listaFrases.add("Juro que não poderia te amar mais do que amo agora, mas sei que amarei amanhã.");
        listaFrases.add("Em sua vida vivem meus sonhos infinitos.");
        listaFrases.add("Quando te vi me apaixonei e você sorriu porque sabia disso.");
        listaFrases.add("Em todo o mundo, não há coração para mim como o seu. Em todo o mundo, não há amor por você como o meu.");
        listaFrases.add("Eu amo como ela(ele) me faz sentir que tudo é possível, ou que a vida vale a pena.");
        listaFrases.add("Amar ou ter amado, basta. Não pergunte mais nada. Não há outra pérola a ser encontrada nas dobras escuras da vida.");
        listaFrases.add("Você me enfeitiçou de corpo e alma, e eu amo, amo, amo você.");
        listaFrases.add("Se você viver até os cem anos, quero viver até os cem menos um dia, para nunca ter que viver sem você.");
        listaFrases.add("Algumas histórias de amor não são romances épicos. Alguns são contos. Mas isso não os torna menos cheios de amor.");
        listaFrases.add("Você é meu coração, minha vida, meu único pensamento.");
        listaFrases.add("Com o mundo inteiro desmoronando, escolhemos esse momento para nos apaixonar.");
        listaFrases.add("Seja qual for a nossa alma, a dele(a) e a minha são iguais.");
        listaFrases.add("Nunca tive um momento de dúvida. Eu te amo. Eu acredito em você completamente. Você é meu querido(a). Minha razão de vida.");
        listaFrases.add("Você deve ser beijada(o) e frequentemente, e por alguém que sabe como. Eu!");
        listaFrases.add("Se eu te amasse menos, talvez pudesse falar mais sobre isso.");
        listaFrases.add("Eu te amo? Meu Deus, se o seu amor fosse um grão de areia, o meu seria um universo de praias.");
        listaFrases.add("Eu sou quem sou por sua causa.");
        listaFrases.add("Eu só quero que você saiba que você é muito especial ... e a razão pela qual estou te dizendo é que eu não sei se alguém já fez isso.");
        listaFrases.add("Lembre-se, somos apaixonados, então não há problema em me beijar a qualquer momento que você desejar e quiser :)");
        listaFrases.add("Eu te amo. Eu soube no primeiro minuto em que te conheci.");
        listaFrases.add("Amamos com um amor que era mais do que amor.");
        listaFrases.add("Eu te amo contra a razão, contra a promessa, contra a paz, contra a esperança, contra a felicidade, contra todo o desânimo que pudesse existir.");
        listaFrases.add("Se eu sei o que é amor, é por sua causa.");
        listaFrases.add("O amor não é apenas algo que você sente, é algo que você faz.");
        listaFrases.add("Eu te amo não por causa de quem você é, mas por causa de quem eu sou quando estou com você.");
        listaFrases.add("Amor é o que você passou com alguém.");
        listaFrases.add("Amor é quando você conhece alguém que lhe conta algo novo sobre você.");
        listaFrases.add("O amor não domina; ele cultiva");
        listaFrases.add("Estamos mais vivos quando estamos apaixonados.");
        listaFrases.add("Nunca ame ninguém que você trata como se essa pessoa fosse comum.");
        listaFrases.add("Amar é nada para ser amado é algo ... amar e ser amado é tudo.");
        listaFrases.add("Dentro de você eu me perco. Sem você, eu me vejo querendo me perder novamente.");
        listaFrases.add("Todos os dias e noites, minha mente está repleta de pensamentos sobre você. Enquanto o sol continuar a brilhar, você pode ter certeza de que meu coração continuará sendo seu.");
        listaFrases.add("Para sempre é muito tempo, mas não me importaria de passar ao seu lado.");
        listaFrases.add("Dê-me um beijo e eu farei uma serenata para você entre as estrelas. Dê-me seu amor e arrancarei cada estrela para colocá-la a seus pés.");
        listaFrases.add("Mal posso esperar ... para passar o resto da minha vida com você.");
        listaFrases.add("Eu olho para você e vejo o resto da minha vida diante dos meus olhos.");
        listaFrases.add("Eu amo seus abraços onde você simplesmente não quer deixar-me ir.");
        listaFrases.add("Eu amo você a cada passo que caminho.");
        listaFrases.add("Eu te amo por tudo o que você é, tudo o que você foi e tudo o que ainda vai ser.");
        listaFrases.add("Eu te amo desde o primeiro dia.");
        listaFrases.add("Te amei ontem, ainda te amo. Sempre amei e sempre irei amar.");
        listaFrases.add("Eu nunca quis ser sua vida inteira - apenas sua parte favorita.");
        listaFrases.add("Eu vi que você era perfeito(a) e então te amei. Então eu vi que você não era perfeito(a) e te amei ainda mais.");
        listaFrases.add("Eu quero estar em seus braços, onde você me abraça forte e nunca me deixa ir.");
        listaFrases.add("Eu quero estar com você até o sol cair no céu.");
        listaFrases.add("Eu quero você. Tudo em você. Suas falhas. Seus erros. Suas imperfeições. Eu quero você e somente você.");
        listaFrases.add("Eu andaria pelo deserto, eu andaria pelo corredor, eu nadaria todos os oceanos só para ver você sorrir.");
        listaFrases.add("Se o nosso amor fosse um livro de histórias, nos encontraríamos na primeira página.");
        listaFrases.add("Se você fosse um filme, eu assistiria você indefinidamente. Eu poderia assistir você todos os dias da minha vida e nunca ficar entediado.");
        listaFrases.add("Sou muito mais eu quando estou com você.");
        listaFrases.add("Meu coração é perfeito porque você está dentro dele.");
        listaFrases.add("Minha mente pensa em você no segundo em que adormeço e assim que acordo todas as manhãs.");
        listaFrases.add("Pensar em você me mantém acordado. Sonhar com você me mantém dormindo. Estar com você me mantém vivo.");
        listaFrases.add("Espero que saiba que toda vez que eu digo para você chegar em casa em segurança, se aquecer, ter um bom dia ou dormir bem, o que realmente estou dizendo é que te amo. Eu te amo tanto que estou começando a roubar o significado de outras palavras.");
        listaFrases.add("Quando eu olho profundamente em sua mente, encontro a beleza de mil diamantes. Enquanto eu deixava aquele amor e beleza inundarem meu corpo, eu sabia que não havia nada pelo qual eu trocaria nosso relacionamento.");
        listaFrases.add("Quando digo que te amo, não digo por hábito. Digo isso para lembrá-lo de que você é a melhor coisa que já me aconteceu.");
        listaFrases.add("Quando você se sentir sozinho(a), basta olhar para os espaços entre seus dedos e lembrar que é onde os meus se encaixam perfeitamente.");
        listaFrases.add("Sempre que você estiver tendo um dia ruim, lembre-se disto: EU TE AMO.");
        listaFrases.add("Você é meu melhor amigo(amiga), meu diário humano e minha outra metade. Você significa o mundo para mim e eu te amo.");
        listaFrases.add("Você é meu mundo!!!");
        listaFrases.add("Você NÃO tem ideia de como meu coração dispara quando vejo você.");
        listaFrases.add("Você nunca deixa de me surpreender. Todos os dias há algo novo que me faz amá-lo ainda mais do que no dia anterior.");
        listaFrases.add("Não me insista para deixá-lo ou voltar atrás de você. Onde você for, eu irei. Onde você ficar, eu ficarei.");
        listaFrases.add("Você é meu templo. Você é meu padre. Você é minha oração. Você é minha libertação.");
        listaFrases.add("Eu preferia ter você por um pouco de tempo do que por nada. Vou lembrar de você perfeitamente. Minha memória vai tocar sua pele, seus lábios. A memória vai doer, mas será minha. ");
        listaFrases.add("Não importa o que aconteça, eu nunca, nem em mil resultados trágicos, nunca me arrependerei de te amar");
        listaFrases.add("Eu quero tudo com você. Eu quero você. Eu quero isso para sempre.");
        listaFrases.add("Eu não vou longe. Eu sempre estarei aqui. Apenas um centímetro de distância. Eu prometo");
        listaFrases.add("O amor deve parecer a primeira vez que você galope um cavalo. Deve fazer seu sangue cantar. Deve assustar você. E alguma parte de você deve reconhecê-lo na primeira vez que encontrar os olhos da outra pessoa. ");
        listaFrases.add("Beijar você é meu hobby favorito. Segurar você é meu passatempo favorito.");
        listaFrases.add("De tirar o fôlego deve significar VOCÊ no dicionário.");
        listaFrases.add("Não faz muito tempo eu estava sozinho e perdido, e então você apareceu e eu estava em casa. Obrigado por me encontrar.");
        listaFrases.add("Certamente, estou sendo recompensado porque tenho você.");
        listaFrases.add("Em seus braços amorosos está o paraíso na terra.");
        listaFrases.add("Você pode não ser perfeito, você é imperfeito como todos os humanos. Mas você é perfeito para mim e isso é o que importa.");
        listaFrases.add("Prometo cuidar do seu coração com cuidado e guardá-lo com amor.");
        listaFrases.add("Ninguém jamais saberá como você é perfeito para mim.");
        listaFrases.add("Você vai caber perfeitamente confortável em meus braços por toda a eternidade, meu amor.");
        listaFrases.add("Eu vou caminhar com você e te seguir até o fim. Você é o vencedor e o único dono do meu coração.");
        listaFrases.add("O poder do seu sorriso nunca deve ser subestimado. Isso derrete meu coração e toca minha alma.");
        listaFrases.add("Seu sorriso é inebriante. Isso perdura, cativa meu coração.");
        listaFrases.add("Uma e outra vez eu tenho que me beliscar quando vejo você ao meu lado. Você é meu sonho tornado realidade.");
        listaFrases.add("Você é único(a) para mim. Nunca tive tanta certeza de nada em toda a minha vida.");
        listaFrases.add("Esperei tanto pela pessoa perfeita e minha paciência finalmente valeu a pena.");
        listaFrases.add("Você não pode fazer nada de errado aos meus olhos. Você é perfeito!");
        listaFrases.add("Posso não ser perfeito, mas sempre deixo você estar certo. E eu sei que não estou errado sobre isso!");
        listaFrases.add("Eu te amo mais do que amo ficar bêbado. E eu realmente adoro ficar bêbado.");

        listaFrases.add("Acho que a perfeição do amor é que ele não é perfeito.");
        listaFrases.add("As melhores e mais belas coisas deste mundo não podem ser vistas ou ouvidas, mas devem ser sentidas com o coração.");
        listaFrases.add("A vida sem amor é como uma árvore sem flores ou frutos.");
        listaFrases.add("A melhor coisa para se agarrar na vida são uns aos outros.");
        listaFrases.add("É melhor ter amado e perdido tempo do que nunca ter amado.");
        listaFrases.add("Você sabe que está apaixonado quando não consegue dormir porque a realidade é finalmente melhor do que seus sonhos.");
        listaFrases.add("O amor não reconhece barreiras. Ele pula obstáculos, pula cercas, penetra paredes para chegar ao seu destino cheio de esperança.");
        listaFrases.add("Ser profundamente amado por alguém lhe dá força, enquanto amar alguém profundamente lhe dá coragem.");
        listaFrases.add("O verdadeiro amante é o homem(a mulher) que pode emocioná-lo beijando sua testa, sorrindo em seus olhos ou apenas olhando para o nada.");
        listaFrases.add("Tudo o que você precisa é amor. Mas um pouco de chocolate de vez em quando não faz mal.");
        listaFrases.add("Juro que não poderia te amar mais do que amo agora, mas sei que amarei amanhã.");
        listaFrases.add("Em sua vida vivem meus sonhos infinitos.");
        listaFrases.add("Quando te vi me apaixonei e você sorriu porque sabia disso.");
        listaFrases.add("Em todo o mundo, não há coração para mim como o seu. Em todo o mundo, não há amor por você como o meu.");
        listaFrases.add("Eu amo como ela(ele) me faz sentir que tudo é possível, ou que a vida vale a pena.");
        listaFrases.add("Amar ou ter amado, basta. Não pergunte mais nada. Não há outra pérola a ser encontrada nas dobras escuras da vida.");
        listaFrases.add("Você me enfeitiçou de corpo e alma, e eu amo, amo, amo você.");
        listaFrases.add("Se você viver até os cem anos, quero viver até os cem menos um dia, para nunca ter que viver sem você.");
        listaFrases.add("Algumas histórias de amor não são romances épicos. Alguns são contos. Mas isso não os torna menos cheios de amor.");
        listaFrases.add("Você é meu coração, minha vida, meu único pensamento.");
        listaFrases.add("Com o mundo inteiro desmoronando, escolhemos esse momento para nos apaixonar.");
        listaFrases.add("Seja qual for a nossa alma, a dele(a) e a minha são iguais.");
        listaFrases.add("Nunca tive um momento de dúvida. Eu te amo. Eu acredito em você completamente. Você é meu querido(a). Minha razão de vida.");
        listaFrases.add("Você deve ser beijada(o) e frequentemente, e por alguém que sabe como. Eu!");
        listaFrases.add("Se eu te amasse menos, talvez pudesse falar mais sobre isso.");
        listaFrases.add("Eu te amo? Meu Deus, se o seu amor fosse um grão de areia, o meu seria um universo de praias.");
        listaFrases.add("Eu sou quem sou por sua causa.");
        listaFrases.add("Eu só quero que você saiba que você é muito especial ... e a razão pela qual estou te dizendo é que eu não sei se alguém já fez isso.");
        listaFrases.add("Lembre-se, somos apaixonados, então não há problema em me beijar a qualquer momento que você desejar e quiser :)");
        listaFrases.add("Eu te amo. Eu soube no primeiro minuto em que te conheci.");
        listaFrases.add("Amamos com um amor que era mais do que amor.");
        listaFrases.add("Eu te amo contra a razão, contra a promessa, contra a paz, contra a esperança, contra a felicidade, contra todo o desânimo que pudesse existir.");
        listaFrases.add("Se eu sei o que é amor, é por sua causa.");
        listaFrases.add("O amor não é apenas algo que você sente, é algo que você faz.");
        listaFrases.add("Eu te amo não por causa de quem você é, mas por causa de quem eu sou quando estou com você.");
        listaFrases.add("Amor é o que você passou com alguém.");
        listaFrases.add("Amor é quando você conhece alguém que lhe conta algo novo sobre você.");
        listaFrases.add("O amor não domina; ele cultiva");
        listaFrases.add("Estamos mais vivos quando estamos apaixonados.");
        listaFrases.add("Nunca ame ninguém que você trata como se essa pessoa fosse comum.");
        listaFrases.add("Amar é nada para ser amado é algo ... amar e ser amado é tudo.");
        listaFrases.add("Dentro de você eu me perco. Sem você, eu me vejo querendo me perder novamente.");
        listaFrases.add("Todos os dias e noites, minha mente está repleta de pensamentos sobre você. Enquanto o sol continuar a brilhar, você pode ter certeza de que meu coração continuará sendo seu.");
        listaFrases.add("Para sempre é muito tempo, mas não me importaria de passar ao seu lado.");
        listaFrases.add("Dê-me um beijo e eu farei uma serenata para você entre as estrelas. Dê-me seu amor e arrancarei cada estrela para colocá-la a seus pés.");
        listaFrases.add("Mal posso esperar ... para passar o resto da minha vida com você.");
        listaFrases.add("Eu olho para você e vejo o resto da minha vida diante dos meus olhos.");
        listaFrases.add("Eu amo seus abraços onde você simplesmente não quer deixar-me ir.");
        listaFrases.add("Eu amo você a cada passo que caminho.");
        listaFrases.add("Eu te amo por tudo o que você é, tudo o que você foi e tudo o que ainda vai ser.");
        listaFrases.add("Eu te amo desde o primeiro dia.");
        listaFrases.add("Te amei ontem, ainda te amo. Sempre amei e sempre irei amar.");
        listaFrases.add("Eu nunca quis ser sua vida inteira - apenas sua parte favorita.");
        listaFrases.add("Eu vi que você era perfeito(a) e então te amei. Então eu vi que você não era perfeito(a) e te amei ainda mais.");
        listaFrases.add("Eu quero estar em seus braços, onde você me abraça forte e nunca me deixa ir.");
        listaFrases.add("Eu quero estar com você até o sol cair no céu.");
        listaFrases.add("Eu quero você. Tudo em você. Suas falhas. Seus erros. Suas imperfeições. Eu quero você e somente você.");
        listaFrases.add("Eu andaria pelo deserto, eu andaria pelo corredor, eu nadaria todos os oceanos só para ver você sorrir.");
        listaFrases.add("Se o nosso amor fosse um livro de histórias, nos encontraríamos na primeira página.");
        listaFrases.add("Se você fosse um filme, eu assistiria você indefinidamente. Eu poderia assistir você todos os dias da minha vida e nunca ficar entediado.");
        listaFrases.add("Sou muito mais eu quando estou com você.");
        listaFrases.add("Meu coração é perfeito porque você está dentro dele.");
        listaFrases.add("Minha mente pensa em você no segundo em que adormeço e assim que acordo todas as manhãs.");
        listaFrases.add("Pensar em você me mantém acordado. Sonhar com você me mantém dormindo. Estar com você me mantém vivo.");
        listaFrases.add("Espero que saiba que toda vez que eu digo para você chegar em casa em segurança, se aquecer, ter um bom dia ou dormir bem, o que realmente estou dizendo é que te amo. Eu te amo tanto que estou começando a roubar o significado de outras palavras.");
        listaFrases.add("Quando eu olho profundamente em sua mente, encontro a beleza de mil diamantes. Enquanto eu deixava aquele amor e beleza inundarem meu corpo, eu sabia que não havia nada pelo qual eu trocaria nosso relacionamento.");
        listaFrases.add("Quando digo que te amo, não digo por hábito. Digo isso para lembrá-lo de que você é a melhor coisa que já me aconteceu.");
        listaFrases.add("Quando você se sentir sozinho(a), basta olhar para os espaços entre seus dedos e lembrar que é onde os meus se encaixam perfeitamente.");
        listaFrases.add("Sempre que você estiver tendo um dia ruim, lembre-se disto: EU TE AMO.");
        listaFrases.add("Você é meu melhor amigo(amiga), meu diário humano e minha outra metade. Você significa o mundo para mim e eu te amo.");
        listaFrases.add("Você é meu mundo!!!");
        listaFrases.add("Você NÃO tem ideia de como meu coração dispara quando vejo você.");
        listaFrases.add("Você nunca deixa de me surpreender. Todos os dias há algo novo que me faz amá-lo ainda mais do que no dia anterior.");
        listaFrases.add("Não me insista para deixá-lo ou voltar atrás de você. Onde você for, eu irei. Onde você ficar, eu ficarei.");
        listaFrases.add("Você é meu templo. Você é meu padre. Você é minha oração. Você é minha libertação.");
        listaFrases.add("Eu preferia ter você por um pouco de tempo do que por nada. Vou lembrar de você perfeitamente. Minha memória vai tocar sua pele, seus lábios. A memória vai doer, mas será minha. ");
        listaFrases.add("Não importa o que aconteça, eu nunca, nem em mil resultados trágicos, nunca me arrependerei de te amar");
        listaFrases.add("Eu quero tudo com você. Eu quero você. Eu quero isso para sempre.");
        listaFrases.add("Eu não vou longe. Eu sempre estarei aqui. Apenas um centímetro de distância. Eu prometo");
        listaFrases.add("O amor deve parecer a primeira vez que você galope um cavalo. Deve fazer seu sangue cantar. Deve assustar você. E alguma parte de você deve reconhecê-lo na primeira vez que encontrar os olhos da outra pessoa. ");
        listaFrases.add("Beijar você é meu hobby favorito. Segurar você é meu passatempo favorito.");
        listaFrases.add("De tirar o fôlego deve significar VOCÊ no dicionário.");
        listaFrases.add("Não faz muito tempo eu estava sozinho e perdido, e então você apareceu e eu estava em casa. Obrigado por me encontrar.");
        listaFrases.add("Certamente, estou sendo recompensado porque tenho você.");
        listaFrases.add("Em seus braços amorosos está o paraíso na terra.");
        listaFrases.add("Você pode não ser perfeito, você é imperfeito como todos os humanos. Mas você é perfeito para mim e isso é o que importa.");
        listaFrases.add("Prometo cuidar do seu coração com cuidado e guardá-lo com amor.");
        listaFrases.add("Ninguém jamais saberá como você é perfeito para mim.");
        listaFrases.add("Você vai caber perfeitamente confortável em meus braços por toda a eternidade, meu amor.");
        listaFrases.add("Eu vou caminhar com você e te seguir até o fim. Você é o vencedor e o único dono do meu coração.");
        listaFrases.add("O poder do seu sorriso nunca deve ser subestimado. Isso derrete meu coração e toca minha alma.");
        listaFrases.add("Seu sorriso é inebriante. Isso perdura, cativa meu coração.");
        listaFrases.add("Uma e outra vez eu tenho que me beliscar quando vejo você ao meu lado. Você é meu sonho tornado realidade.");
        listaFrases.add("Você é único(a) para mim. Nunca tive tanta certeza de nada em toda a minha vida.");
        listaFrases.add("Esperei tanto pela pessoa perfeita e minha paciência finalmente valeu a pena.");
        listaFrases.add("Você não pode fazer nada de errado aos meus olhos. Você é perfeito!");
        listaFrases.add("Posso não ser perfeito, mas sempre deixo você estar certo. E eu sei que não estou errado sobre isso!");
        listaFrases.add("Eu te amo mais do que amo ficar bêbado. E eu realmente adoro ficar bêbado.");

        listaFrases.add("Acho que a perfeição do amor é que ele não é perfeito.");
        listaFrases.add("As melhores e mais belas coisas deste mundo não podem ser vistas ou ouvidas, mas devem ser sentidas com o coração.");
        listaFrases.add("A vida sem amor é como uma árvore sem flores ou frutos.");
        listaFrases.add("A melhor coisa para se agarrar na vida são uns aos outros.");
        listaFrases.add("É melhor ter amado e perdido tempo do que nunca ter amado.");
        listaFrases.add("Você sabe que está apaixonado quando não consegue dormir porque a realidade é finalmente melhor do que seus sonhos.");
        listaFrases.add("O amor não reconhece barreiras. Ele pula obstáculos, pula cercas, penetra paredes para chegar ao seu destino cheio de esperança.");
        listaFrases.add("Ser profundamente amado por alguém lhe dá força, enquanto amar alguém profundamente lhe dá coragem.");
        listaFrases.add("O verdadeiro amante é o homem(a mulher) que pode emocioná-lo beijando sua testa, sorrindo em seus olhos ou apenas olhando para o nada.");
        listaFrases.add("Tudo o que você precisa é amor. Mas um pouco de chocolate de vez em quando não faz mal.");
        listaFrases.add("Juro que não poderia te amar mais do que amo agora, mas sei que amarei amanhã.");
        listaFrases.add("Em sua vida vivem meus sonhos infinitos.");
        listaFrases.add("Quando te vi me apaixonei e você sorriu porque sabia disso.");
        listaFrases.add("Em todo o mundo, não há coração para mim como o seu. Em todo o mundo, não há amor por você como o meu.");
        listaFrases.add("Eu amo como ela(ele) me faz sentir que tudo é possível, ou que a vida vale a pena.");
        listaFrases.add("Amar ou ter amado, basta. Não pergunte mais nada. Não há outra pérola a ser encontrada nas dobras escuras da vida.");
        listaFrases.add("Você me enfeitiçou de corpo e alma, e eu amo, amo, amo você.");
        listaFrases.add("Se você viver até os cem anos, quero viver até os cem menos um dia, para nunca ter que viver sem você.");
        listaFrases.add("Algumas histórias de amor não são romances épicos. Alguns são contos. Mas isso não os torna menos cheios de amor.");
        listaFrases.add("Você é meu coração, minha vida, meu único pensamento.");
        listaFrases.add("Com o mundo inteiro desmoronando, escolhemos esse momento para nos apaixonar.");
        listaFrases.add("Seja qual for a nossa alma, a dele(a) e a minha são iguais.");
        listaFrases.add("Nunca tive um momento de dúvida. Eu te amo. Eu acredito em você completamente. Você é meu querido(a). Minha razão de vida.");
        listaFrases.add("Você deve ser beijada(o) e frequentemente, e por alguém que sabe como. Eu!");
        listaFrases.add("Se eu te amasse menos, talvez pudesse falar mais sobre isso.");
        listaFrases.add("Eu te amo? Meu Deus, se o seu amor fosse um grão de areia, o meu seria um universo de praias.");
        listaFrases.add("Eu sou quem sou por sua causa.");
        listaFrases.add("Eu só quero que você saiba que você é muito especial ... e a razão pela qual estou te dizendo é que eu não sei se alguém já fez isso.");
        listaFrases.add("Lembre-se, somos apaixonados, então não há problema em me beijar a qualquer momento que você desejar e quiser :)");
        listaFrases.add("Eu te amo. Eu soube no primeiro minuto em que te conheci.");
        listaFrases.add("Amamos com um amor que era mais do que amor.");
        listaFrases.add("Eu te amo contra a razão, contra a promessa, contra a paz, contra a esperança, contra a felicidade, contra todo o desânimo que pudesse existir.");
        listaFrases.add("Se eu sei o que é amor, é por sua causa.");
        listaFrases.add("O amor não é apenas algo que você sente, é algo que você faz.");
        listaFrases.add("Eu te amo não por causa de quem você é, mas por causa de quem eu sou quando estou com você.");
        listaFrases.add("Amor é o que você passou com alguém.");
        listaFrases.add("Amor é quando você conhece alguém que lhe conta algo novo sobre você.");
        listaFrases.add("O amor não domina; ele cultiva");
        listaFrases.add("Estamos mais vivos quando estamos apaixonados.");
        listaFrases.add("Nunca ame ninguém que você trata como se essa pessoa fosse comum.");
        listaFrases.add("Amar é nada para ser amado é algo ... amar e ser amado é tudo.");
        listaFrases.add("Dentro de você eu me perco. Sem você, eu me vejo querendo me perder novamente.");
        listaFrases.add("Todos os dias e noites, minha mente está repleta de pensamentos sobre você. Enquanto o sol continuar a brilhar, você pode ter certeza de que meu coração continuará sendo seu.");
        listaFrases.add("Para sempre é muito tempo, mas não me importaria de passar ao seu lado.");
        listaFrases.add("Dê-me um beijo e eu farei uma serenata para você entre as estrelas. Dê-me seu amor e arrancarei cada estrela para colocá-la a seus pés.");
        listaFrases.add("Mal posso esperar ... para passar o resto da minha vida com você.");
        listaFrases.add("Eu olho para você e vejo o resto da minha vida diante dos meus olhos.");
        listaFrases.add("Eu amo seus abraços onde você simplesmente não quer deixar-me ir.");
        listaFrases.add("Eu amo você a cada passo que caminho.");
        listaFrases.add("Eu te amo por tudo o que você é, tudo o que você foi e tudo o que ainda vai ser.");
        listaFrases.add("Eu te amo desde o primeiro dia.");
        listaFrases.add("Te amei ontem, ainda te amo. Sempre amei e sempre irei amar.");
        listaFrases.add("Eu nunca quis ser sua vida inteira - apenas sua parte favorita.");
        listaFrases.add("Eu vi que você era perfeito(a) e então te amei. Então eu vi que você não era perfeito(a) e te amei ainda mais.");
        listaFrases.add("Eu quero estar em seus braços, onde você me abraça forte e nunca me deixa ir.");
        listaFrases.add("Eu quero estar com você até o sol cair no céu.");
        listaFrases.add("Eu quero você. Tudo em você. Suas falhas. Seus erros. Suas imperfeições. Eu quero você e somente você.");
        listaFrases.add("Eu andaria pelo deserto, eu andaria pelo corredor, eu nadaria todos os oceanos só para ver você sorrir.");
        listaFrases.add("Se o nosso amor fosse um livro de histórias, nos encontraríamos na primeira página.");
        listaFrases.add("Se você fosse um filme, eu assistiria você indefinidamente. Eu poderia assistir você todos os dias da minha vida e nunca ficar entediado.");
        listaFrases.add("Sou muito mais eu quando estou com você.");
        listaFrases.add("Meu coração é perfeito porque você está dentro dele.");
        listaFrases.add("Minha mente pensa em você no segundo em que adormeço e assim que acordo todas as manhãs.");
        listaFrases.add("Pensar em você me mantém acordado. Sonhar com você me mantém dormindo. Estar com você me mantém vivo.");
        listaFrases.add("Espero que saiba que toda vez que eu digo para você chegar em casa em segurança, se aquecer, ter um bom dia ou dormir bem, o que realmente estou dizendo é que te amo. Eu te amo tanto que estou começando a roubar o significado de outras palavras.");
        listaFrases.add("Quando eu olho profundamente em sua mente, encontro a beleza de mil diamantes. Enquanto eu deixava aquele amor e beleza inundarem meu corpo, eu sabia que não havia nada pelo qual eu trocaria nosso relacionamento.");
        listaFrases.add("Quando digo que te amo, não digo por hábito. Digo isso para lembrá-lo de que você é a melhor coisa que já me aconteceu.");
        listaFrases.add("Quando você se sentir sozinho(a), basta olhar para os espaços entre seus dedos e lembrar que é onde os meus se encaixam perfeitamente.");
        listaFrases.add("Sempre que você estiver tendo um dia ruim, lembre-se disto: EU TE AMO.");
        listaFrases.add("Você é meu melhor amigo(amiga), meu diário humano e minha outra metade. Você significa o mundo para mim e eu te amo.");
        listaFrases.add("Você é meu mundo!!!");
        listaFrases.add("Você NÃO tem ideia de como meu coração dispara quando vejo você.");
        listaFrases.add("Você nunca deixa de me surpreender. Todos os dias há algo novo que me faz amá-lo ainda mais do que no dia anterior.");
        listaFrases.add("Não me insista para deixá-lo ou voltar atrás de você. Onde você for, eu irei. Onde você ficar, eu ficarei.");
        listaFrases.add("Você é meu templo. Você é meu padre. Você é minha oração. Você é minha libertação.");
        listaFrases.add("Eu preferia ter você por um pouco de tempo do que por nada. Vou lembrar de você perfeitamente. Minha memória vai tocar sua pele, seus lábios. A memória vai doer, mas será minha. ");
        listaFrases.add("Não importa o que aconteça, eu nunca, nem em mil resultados trágicos, nunca me arrependerei de te amar");
        listaFrases.add("Eu quero tudo com você. Eu quero você. Eu quero isso para sempre.");
        listaFrases.add("Eu não vou longe. Eu sempre estarei aqui. Apenas um centímetro de distância. Eu prometo");
        listaFrases.add("O amor deve parecer a primeira vez que você galope um cavalo. Deve fazer seu sangue cantar. Deve assustar você. E alguma parte de você deve reconhecê-lo na primeira vez que encontrar os olhos da outra pessoa. ");
        listaFrases.add("Beijar você é meu hobby favorito. Segurar você é meu passatempo favorito.");
        listaFrases.add("De tirar o fôlego deve significar VOCÊ no dicionário.");
        listaFrases.add("Não faz muito tempo eu estava sozinho e perdido, e então você apareceu e eu estava em casa. Obrigado por me encontrar.");
        listaFrases.add("Certamente, estou sendo recompensado porque tenho você.");
        listaFrases.add("Em seus braços amorosos está o paraíso na terra.");
        listaFrases.add("Você pode não ser perfeito, você é imperfeito como todos os humanos. Mas você é perfeito para mim e isso é o que importa.");
        listaFrases.add("Prometo cuidar do seu coração com cuidado e guardá-lo com amor.");
        listaFrases.add("Ninguém jamais saberá como você é perfeito para mim.");
        listaFrases.add("Você vai caber perfeitamente confortável em meus braços por toda a eternidade, meu amor.");
        listaFrases.add("Eu vou caminhar com você e te seguir até o fim. Você é o vencedor e o único dono do meu coração.");
        listaFrases.add("O poder do seu sorriso nunca deve ser subestimado. Isso derrete meu coração e toca minha alma.");
        listaFrases.add("Seu sorriso é inebriante. Isso perdura, cativa meu coração.");
        listaFrases.add("Uma e outra vez eu tenho que me beliscar quando vejo você ao meu lado. Você é meu sonho tornado realidade.");
        listaFrases.add("Você é único(a) para mim. Nunca tive tanta certeza de nada em toda a minha vida.");
        listaFrases.add("Esperei tanto pela pessoa perfeita e minha paciência finalmente valeu a pena.");
        listaFrases.add("Você não pode fazer nada de errado aos meus olhos. Você é perfeito!");
        listaFrases.add("Posso não ser perfeito, mas sempre deixo você estar certo. E eu sei que não estou errado sobre isso!");
        listaFrases.add("Eu te amo mais do que amo ficar bêbado. E eu realmente adoro ficar bêbado.");

        Calendar calendar = Calendar.getInstance();
        int selected = calendar.get(Calendar.DAY_OF_YEAR);
        txtFraseAmor.setText(listaFrases.get(selected));
    }
}