package com.e4u.autoajuda.activities;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.ImageView;
import android.widget.TextView;

import com.e4u.autoajuda.R;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

public class FraseDiaActivity extends AppCompatActivity {

    TextView txtFrase;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_frase_dia);

        //Criar o vinculo entre as variaveis e os objetos do XML
        txtFrase = findViewById(R.id.txtFrase);

        carregarFrases();
    }

    private void carregarFrases(){

        List<String> listaFrases = new ArrayList<>();

        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");



        // DUPLICADAS
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");
        listaFrases.add("“Todos os nossos sonhos podem se tornar realidade, se tivermos a coragem de persegui-los.” - Walt Disney");
        listaFrases.add("“O segredo de ficar à frente é começar.” - Mark Twain");
        listaFrases.add("“Já perdi mais de 9.000 arremessos em minha carreira. Perdi quase 300 jogos. 26 vezes eu fui confiável para dar a chance à vitória e errar. Eu falhei várias e várias vezes na minha vida e é por isso que tenho sucesso.” - Michael Jordan");
        listaFrases.add("“Não se limite. Muitas pessoas se limitam ao que pensam que podem fazer. Você pode ir tão longe quanto sua mente permitir. O que você acredita, lembre-se, você pode alcançar.” - Mary Kay Ash");
        listaFrases.add("“A melhor época para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.”");
        listaFrases.add("“É difícil vencer uma pessoa que nunca desiste.”- Babe Ruth");
        listaFrases.add("“Acordo todas as manhãs e penso comigo mesma, 'até onde posso levar esta empresa nas próximas 24 horas.” - Leah Busque");
        listaFrases.add("“Se as pessoas estão duvidando do quão longe você pode ir, vá tão longe que não possa mais ouvi-las.” - Michele Ruiz");
        listaFrases.add("“Precisamos aceitar que nem sempre tomaremos as decisões certas, que às vezes erraremos muito - entender que o fracasso não é o oposto do sucesso, é parte do sucesso.”- Arianna Huffington");
        listaFrases.add("“Você tem que dançar como se não houvesse ninguém olhando, ame como se nunca fosse machucado, cante como se não houvesse ninguém ouvindo e viva como se fosse o paraíso na terra.”");
        listaFrases.add("“Os contos de fadas são mais que verdadeiros: não porque nos dizem que dragões existem, mas porque nos dizem que dragões podem ser vencidos.”");
        listaFrases.add("“Tudo o que você pode imaginar é real.” - Pablo Picasso");
        listaFrases.add("“Quando uma porta de felicidade se fecha, outra se abre; mas muitas vezes olhamos tanto para a porta fechada que não vemos aquela que se abriu para nós.”");
        listaFrases.add("“Faça todos os dias uma coisa que te assuste.”");
        listaFrases.add("“Pessoas inteligentes aprendem com tudo e todos, pessoas comuns com suas experiências, pessoas estúpidas já têm todas as respostas.” - Sócrates");
        listaFrases.add("“Faça o que achar certo em seu coração - pois você será criticado de qualquer maneira.”");
        listaFrases.add("“Felicidade não é algo pronto. Isso vem de suas próprias ações.”");
        listaFrases.add("“O que quer que você seja, seja o melhor.”- Abraham Lincoln");
        listaFrases.add("“A mesma água fervente que amolece a batata endurece o ovo. É disso que você é feito. Não as circunstâncias. ”");
        listaFrases.add("“Se tivermos a atitude de que vai ser um grande dia, geralmente é.”");
        listaFrases.add("“Você pode experimentar a dor da disciplina ou a dor do arrependimento. A escolha é sua.”");

        //listaFrases.add("“”");

        int selected = Calendar.DAY_OF_YEAR;
        txtFrase.setText(listaFrases.get(selected));
    }
}